### ISSUE TITLE
delete /api/* needs to clean other associated data

### ISSUE THREAD

**Issue by CharlieMartell** [alkalai2/CrowdSauce#37]
Currently 
deleting a user should delete:
- all posts associated with that user
- all favorites on those posts
- all tags on those posts

deleting a post should delete:
- all favorites on that post
- all tags on that post

And in any other cases you see it should be clear workflow.

**Comment by HarryZXJ** [comment]
1221933cdd64e559f8417a5a8464f62e366a65f4
