### ISSUE TITLE
'GET' Account has not been implemented

### ISSUE THREAD

**Issue by jokeefe94** [alkalai2/CrowdSauce#47]
It needs to accept a userID in the body of the request and return back that userId and that user's name

**Comment by CharlieMartell** [comment]
Get accounts is actually currently implemented if you wanted to get a specific users account you would make a request like GET /api/accounts/?userId=XXXX, however we have made a change where you will receive the name of the user in the feed so you will likely not need this at this time. @jokeefe94

**Comment by CharlieMartell** [comment]
Should be completed
