### ISSUE TITLE
CrowdSauce should request user_friends permission on login

### ISSUE THREAD

**Issue by CharlieMartell** [alkalai2/CrowdSauce#60]
Currently with real users most/all? block user_friends permission so we cannot get friends posts in the application. This needs to be fixed so that it requests application permissions.

**Comment by lupuchard** [comment]
Done: dfc5841b40b76ff39ecee68b1046ce81361fb644

**Comment by CharlieMartell** [comment]
I think this issue is the same as #69 which seems to be working, I think we should probably lose this.
