### ISSUE TITLE
Friends for real people not working

### ISSUE THREAD

**Issue by CharlieMartell** [alkalai2/CrowdSauce#69]
Currently when logged in as a real facebook user, your friends will not show up even if they have used the application.

**Comment by alkalai2** [comment]
@alex565656 assigning this to you

**Comment by CharlieMartell** [comment]
@alex565656 @alkalai2 This seems to have been fixed not sure what the commit sha was, but I seem to have my friends correctly populated upon logging in.

**Comment by alex565656** [comment]
It does not seem to be working for me. Just wondering, but which names are displayed? I dont have everyone on my friends list.

**Comment by CharlieMartell** [comment]
@alex565656 It works for real people that have accepted the permissions on the application and used it before, I made a fake facebook user and gave them permissions to use the app(since its in dev mode) and was able to use it and it populates correctly. I will message the login info of the test user to you on slack so you can try.
