### ISSUE TITLE
About Page is still Lorem Ipsum

### ISSUE THREAD

**Issue by CharlieMartell** [alkalai2/CrowdSauce#70]
Our about page is still meaningless and ugly.

**Comment by alkalai2** [comment]
@jokeefe94 adding you in this. We should write something up

**Comment by jokeefe94** [comment]
I changed the content to relevant information about CrowdSauce. Do we think the existing style is okay? Did I write up enough information about CrowdSauce?

**Comment by alkalai2** [comment]
I think its good for now

**Comment by CharlieMartell** [comment]
Were these changes on a branch other than master, still lorem ipsum as far as I can tell.
